import {
  AccessAlarmOutlined,
  AirOutlined,
  CabinOutlined,
  ConstructionOutlined,
  CropSquareOutlined,
  DeviceThermostatOutlined,
  DirectionsCar,
  ElectricBoltOutlined,
  FireplaceOutlined,
  FoundationOutlined,
  GarageOutlined,
  GasMeterOutlined,
  HeatPumpOutlined,
  LocalFloristOutlined,
  RoofingOutlined,
  SignalWifi4BarOutlined,
  SquareFootOutlined,
  SquareOutlined,
  StairsOutlined,
  TableChart,
  TvOffOutlined,
  WarehouseOutlined,
  WaterDamageOutlined,
  WaterOutlined,
  WcOutlined,
} from "@mui/icons-material";
import { SvgIconTypeMap } from "@mui/material";
import { OverridableComponent } from "@mui/material/OverridableComponent";

export const vilaBoxIcons: Record<
  string,
  OverridableComponent<SvgIconTypeMap<{}, "svg">> & {
    muiName: string;
  }
> = {
  geamuriTermopan: DeviceThermostatOutlined,
  apa: WaterOutlined,
  garaj: GarageOutlined,
  pivnita: StairsOutlined,
  incalzireCentrala: HeatPumpOutlined,
  renovatRecent: ConstructionOutlined,
  detectorGaze: GasMeterOutlined,
  termoIzolatie: DeviceThermostatOutlined,
  curentElectric: ElectricBoltOutlined,
  gradina: LocalFloristOutlined,
  acoperisTigla: RoofingOutlined,
  gresie: CropSquareOutlined,
  faianta: SquareOutlined,
  planseeBeton: FoundationOutlined,
  consolidata: ConstructionOutlined,
  wcServiciu: WcOutlined,
  spatiuDepozitare: WarehouseOutlined,
  cabluTV: TvOffOutlined,
  internet: SignalWifi4BarOutlined,
  internetFibraOptica: SignalWifi4BarOutlined,
  pod: RoofingOutlined,
  parchet: CabinOutlined,
  gaz: GasMeterOutlined,
  canalizare: TableChart,
  parcareInCurte: DirectionsCar,
  sistemAlarma: AccessAlarmOutlined,
  sistemIrigatie: WaterDamageOutlined,
  deschidere: SquareFootOutlined,
  suprafataUtila: SquareFootOutlined,
  suprafataTeren: SquareFootOutlined,
  suprafataConstruita: SquareFootOutlined,
  suprafataDesfasurata: SquareFootOutlined,
  amprentaLaSol: SquareFootOutlined,
  detectorIncendiu: FireplaceOutlined,
  aerConditionat: AirOutlined,
};

export const vilaBoxText: Record<string, string> = {
  geamuriTermopan: "Geamuri termopan",
  apa: "Apa",
  garaj: "Garaj",
  pivnita: "Pivnita",
  incalzireCentrala: "Incalzire centrala",
  renovatRecent: "Renovat recent",
  detectorGaze: "Detector gaze",
  termoIzolatie: "Termo izolatie",
  curentElectric: "Curent electric",
  gradina: "Gradina",
  acoperisTigla: "Acoperis tigla",
  gresie: "Gresie",
  faianta: "Faianta",
  planseeBeton: "Plansee beton",
  consolidata: "Consolidata",
  wcServiciu: "WC serviciu",
  spatiuDepozitare: "Spatiu depozitare",
  cabluTV: "Cablu TV",
  internet: "Internet",
  internetFibraOptica: "Internet prin fibra optica",
  pod: "Pod",
  parchet: "Parchet",
  gaz: "Gaz",
  canalizare: "Canalizare",
  parcareInCurte: "Parcare in curte",
  sistemAlarma: "Sistem de alarma",
  sistemIrigatie: "Sistem de irigatie",
  deschidere: "Deschidere",
  suprafataUtila: "Suprafata utila",
  suprafataTeren: "Suprafata teren",
  suprafataConstruita: "Suprafata construita",
  suprafataDesfasurata: "Suprafata desfasurata",
  amprentaLaSol: "Amprenta la sol",
  detectorIncendiu: "Detector incendiu",
  aerConditionat: "Aer conditionat",
};
