name: Build Next.js and start
on: push
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install NPM depedencies
      run: npm install
    - name: Build Project Dependencies
      run: npm run build
